services:
  novnc-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novnc-proxy
    ports:
      - "7575:7575"   # HTTP server untuk noVNC client
      - "7576:7576"   # WebSocket proxy port
    environment:
      - NODE_ENV=production
      - HTTP_PORT=7575
      - WEBSOCKET_PORT=7576
      - DEFAULT_VNC_HOST=10.8.10.6
      - DEFAULT_VNC_PORT=5900
    volumes:
      # Mount konfigurasi jika diperlukan
      - ./config:/app/config:ro
      # Mount /etc/hosts dari host
      - /etc/hosts:/etc/hosts:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7575/vnc/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  novnc-network:
    driver: bridge
    # Gunakan default bridge network agar bisa akses host
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"

volumes:
  vnc-data:
    driver: local
