services:
  novnc-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novnc-proxy
    ports:
      - "7575:7575"   # HTTP server untuk noVNC client
      - "7576:7576"   # WebSocket proxy port
    environment:
      - NODE_ENV=production
      - HTTP_PORT=7575
      - WEBSOCKET_PORT=7576
      - DEFAULT_VNC_HOST=10.8.10.6
      - DEFAULT_VNC_PORT=5900
    volumes:
      # Mount konfigurasi jika diperlukan
      - ./config:/app/config:ro
    networks:
      - novnc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7575/vnc/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Contoh service VNC server (opsional)
  # Uncomment jika Anda ingin menjalankan VNC server dalam container
  # vnc-server:
  #   image: dorowu/ubuntu-desktop-lxde-vnc:focal
  #   container_name: vnc-server
  #   ports:
  #     - "5900:5900"   # VNC port
  #     - "6080:6080"   # noVNC web interface (built-in)
  #   environment:
  #     - VNC_PASSWORD=vncpassword
  #     - RESOLUTION=1024x768
  #   volumes:
  #     - vnc-data:/home/ubuntu
  #   networks:
  #     - novnc-network
  #   restart: unless-stopped

networks:
  novnc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  vnc-data:
    driver: local
