services:
  # OpenVPN Client untuk akses ke network VPN
  openvpn-client:
    image: dperson/openvpn-client:latest
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      # Mount file konfigurasi OpenVPN Anda
      - ./vpn-config:/vpn:ro
    environment:
      - VPN_CONFIG=/vpn/client.ovpn
    networks:
      - novnc-network
    restart: unless-stopped
    # Container ini akan handle VPN connection
    command: ["openvpn", "--config", "/vpn/client.ovpn"]

  novnc-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novnc-proxy
    ports:
      - "7575:7575"   # HTTP server untuk noVNC client
      - "7576:7576"   # WebSocket proxy port
    environment:
      - NODE_ENV=production
      - HTTP_PORT=7575
      - WEBSOCKET_PORT=7576
      - DEFAULT_VNC_HOST=10.8.10.6
      - DEFAULT_VNC_PORT=5900
      - DEBUG=true
    volumes:
      # Mount konfigurasi jika diperlukan
      - ./config:/app/config:ro
    networks:
      - novnc-network
    restart: unless-stopped
    # Bergantung pada OpenVPN client
    depends_on:
      - openvpn-client
    # Gunakan network dari OpenVPN container
    network_mode: "container:openvpn-client"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7575/vnc/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  novnc-network:
    driver: bridge

volumes:
  vnc-data:
    driver: local
